#ifndef _QB50_SYS_DEVICE_ADC_H
#define _QB50_SYS_DEVICE_ADC_H

#include <FreeRTOS.h>
#include <semphr.h>

#include "BusDevice.h"
#include "GPIOPin.h"
#include "NVIC.h"
#include "stm32f4xx_adc.h"

//Over-ride macros defined by CMSIS
#undef ADC
#undef ADC1
#undef ADC2
#undef ADC3

namespace qb50{

	class ADC : public BusDevice
	{
	public:

		//Constructor
		ADC(Bus& bus,
			const uint32_t iobase,
			const uint32_t periph,
			const char *name,
			GPIOPin& pin,
			GPIOPin::Mode mode,
			GPIOPin::Channel channel
		);

		//Destructor
		~ADC();

		ADC& init    (void);
		ADC& enable  (void);
		ADC& disable (void);


		uint16_t getValue_adc(); //Get the value generated by the ADC
	private:

		GPIOPin& _pin;
		GPIOPin::Alt  _alt;
		GPIOPin::Mode _mode;
		GPIOPin::Channel _channel;
		uint8_t _numConv;

	};

	extern qb50::ADC SUN1;
	extern qb50::ADC SUN2;
	extern qb50::ADC SUN3;
	extern qb50::ADC SUN4;
	extern qb50::ADC SUN5;
	extern qb50::ADC SUN6;
	extern qb50::ADC SUN7;
	extern qb50::ADC SUN8;
	extern qb50::ADC SUN9;
}

#endif
/* ADC_H_INCLUDED */
